### ISSUE TITLE
Feature request: getblockchaininfo

### ISSUE THREAD

**Issue by majudev** [EXCCoin/exccd#47]
I would love to see the getblockchaininfo command working. Dcrd has implemented it some time ago, so it shouldn't be hard to do (but still too hard for me to do it on my on, since I don't know golang). Is there any chance it will be done in near future?

**Comment by harzo** [comment]
Hello @majudev,
Thank you for your request. We are going to upgrade our version of rpc in the near future, including `getblockchaininfo`. We will try to get it done in the next two weeks. 

In the meantime - could you please specify what data are crucial for you? Maybe we are able to provide some workaround for your case.

**Comment by majudev** [comment]
Hi @harzo ,
I'm trying to set up the mining pool. I'm porting NOMP to work with it, but I realised that `getblockchaininfo` isn't necessary (I used `getinfo` instead). But the problem I'm struggling now with is the `getblocktemplate`, which I wasn't able to find workaround for yet. I don't want to mess with exccd code, since this is far beyond my programming skills. Do you plan to implement `getblocktemplate` as well?

**Comment by harzo** [comment]
Unfortunately `getblocktemplate` won't be implemented because of incompatibility with our (and Decred's) block header. It contains several fields related to Proof of Stake and that's why both coins are using older version of `getblocktemplate` which is `getwork`.

GetWork: 
```
{
  "data": "00000000bf9d58482135c4d8d9445af7604b24ccf1d31b33df33abf21a4e11f52c
000000ef9d462a20d734def40076f0027faa8ef8d9c52d68c46741d03b1732377a556ed9cbf3b
694e65c1b287e8fd2be2e2243a74356d1ef95413d9fc74ffb8a8a07530100e11754a6af500500
03000115000000096f1d28d1354d000000000a0d0000591300009329a55600000000000000000
00000000000000000000000000000000000000000000000000000000000000080000001000000
00000005a0",
  "target": "000000000000000000000000000000000000000000000000000000096f000000"
}
```
Field `data` contains serialized blockheader, so my advice is to create BlockHeader structure with all fields and reading into it from data buffer.

**Comment by majudev** [comment]
Thanks a lot!
